### ISSUE TITLE
Duplicate ID

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/cpp4python#1]
```
/home/bmiller/Runestone/web2py/applications/runestone/books/cpp4python/_sources/Input_and_Output/InputandOutput.rst:287: WARNING: Duplicate ID -- see Input_and_Output/InputandOutput, line 83
/home/bmiller/Runestone/web2py/applications/runestone/books/cpp4python/_sources/IntroCpp/ArrayIteration.cpp:18: WARNING: Definition list ends without a blank line; unexpected unindent.
```

**Comment by bnmnetp** [comment]
@pearcej -- Can you have a look at this duplicate?

**Comment by RustyDotson** [comment]
Hey Brad, I fixed the first issue in your first comment. However, for the second error, the ArrayIteration.cpp file is never used throughout the entire chapter from my understanding. I will make a merge request for the first error, but I think the second error should be another posted issue.

**Comment by RustyDotson** [comment]
#2

**Comment by RustyDotson** [comment]
Okay, this should fix the pavement.py problem from the last pull request. #3
