### ISSUE TITLE
Function 1 and 2 do not have the same behavior. Activity: 4.1.2

### ISSUE THREAD

**Issue by daizenj** [RunestoneInteractive/cpp4python#11]
**What Course are you in**
Knowing the course will help us a lot

cpp4python

**What Page were you on**
Section 4.1 Defining C++ Functions

**What is your username**
njounkengdaizem

**Describe the bug**
A clear and concise description of what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, what's wrong with it?" Could you help them with only that to go on?

Section 4.1, Activity: 4.1.2
Function 1 and 2 do not have the same behavior. They are similar with overlapping things they do.

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

Section 4.1 > Activity: 4.1.2

**Comment by demekenega** [comment]
The section doesn't say both functions are identical; instead, it says they are similar, which means even though their return type is different, they will still give us the same value, which is ten. Also, the section explains their differences.

This issue can be closed. @pearcej
