### ISSUE TITLE
in_stream.open() uses the filename 'myFile.txt" but the image just has myFile.

### ISSUE THREAD

**Issue by maalimsaid** [RunestoneInteractive/cpp4python#12]
**What Course are you in**

cpp4python

**What Page were you on**

section 6.3

**What is your username**

maalims

**Describe the bug**

There is a contrast in the naming of the file. In the text, stream.open() uses the filename 'myFile.txt' but in the picture demonstration, it uses 'myFile' only.

**Traceback**

It's in section 6.3 of the book. The section is called File operations.

**Comment by demekenega** [comment]
.txt is the extension, and the image is just a sample file, which means it can be anything, but for simplicity, they made the extension of the file .txt.

@pearcej this issue can be close.
