### ISSUE TITLE
"we use it’s close() member" should be  'we use its close() member"

### ISSUE THREAD

**Issue by maalimsaid** [RunestoneInteractive/cpp4python#16]
**What Course are you in**
cpp4python

**What Page were you on**
section 6.3

**What is your username**
maalims

**Describe the bug**
This is a simple grammatical error, instead of we use it's close(), it should be we use its close()

**Traceback**
The bug is in section 6.3 in the third paragraph just after the second image, the sentence begins with "To disconnect....."

**Comment by demekenega** [comment]
Working on it.
