### ISSUE TITLE
Section 8.7 - What does this sentence mean? "This is due to the complex handling and of Fonts by operating systems that is far more cumbersome to manage in C++."

### ISSUE THREAD

**Issue by maalimsaid** [RunestoneInteractive/cpp4python#33]
**What Course are you in**
cpp4python

**What Page were you on**
section 8.7

**What is your username**
maalims

**Describe the bug**
This is not a bug, but the wording of the sentence. The sentence, "This is due to the complex handling and of Fonts by operating systems that is far more cumbersome to manage in C++." It would be helpful if the wording can be clear. 

**Traceback**
Section 8.7, on the first sentence of the second paragraph just after the first code.

**Comment by demekenega** [comment]
Working on it.
