### ISSUE TITLE
& is an ampersand not asterisk

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/cpp4python#4]
Error reported in course cpp4python on page AtomicData by user rickyp72 rickyp72@gmail.com
in section 2.5.1.1. The address-of operator,

  "int *ptrN = varN; // Note no asterisk,"

Its is talking about a missing '&' so
 this should be:
 " int *ptrN = varN; // Note no ampersand",

**Comment by bnmnetp** [comment]
@pearcej this is for one of your students

**Comment by pearcej** [comment]
It is now resolved in pearcej/cpp4python and will come through in the next pull request.
