### ISSUE TITLE
Section 7.5 Quiz is wrong. Runtime is an error that happens while a program is executing NOT just when it starts.

### ISSUE THREAD

**Issue by maalimsaid** [RunestoneInteractive/cpp4python#40]
**What Course are you in**
cpp4python

**What Page were you on**
section 7.5

**What is your username**
maalims

**Describe the bug**
The answer to the question is wrong. A runtime error is matched to the wrong answer

**Traceback**
The quiz on section 7.5

**Comment by demekenega** [comment]
Working on it.
