### ISSUE TITLE
Clarification Activity 5.6.1 Section 5.6

### ISSUE THREAD

**Issue by daizenj** [RunestoneInteractive/cpp4python#44]
**What Course are you in**
cpp4python 

**What Page were you on**
Section 5.6

**What is your username**
njounkengdaizem

**Describe the bug**
Why is the find() function for unordered sets not in the table but is mentioned after Activity 5.6.1 when you specifically said that the summary is followed by their use?

If you got here through the Bug Report page and there was a stack trace, please paste it here

**Traceback**
Section 5.6 > Activity: 5.6.1

**Comment by demekenega** [comment]
Working on it.
