### ISSUE TITLE
Fix: Table 6, the name is "add", but the usage is "insert" Section 5.6

### ISSUE THREAD

**Issue by daizenj** [RunestoneInteractive/cpp4python#45]
**What Course are you in**
Knowing the course will help us a lot

cpp4python

**What Page were you on**
Section 5.6

**What is your username**
njounkengdaizem

**Describe the bug**
In table 6, the name is "add", but the usage is "insert"

**Traceback**
Section 5.6 >Table 6

**Comment by demekenega** [comment]
Working on it.
