### ISSUE TITLE
Function Overloading

### ISSUE THREAD

**Issue by daizenj** [RunestoneInteractive/cpp4python#47]
**What Course are you in**
cpp4python

**What Page were you on**
5.6

**What is your username**
njounkengdaizem

**Describe the bug**
Why is Function Overloading at the front of the chapter?

**Traceback**
Section 5.6

**Comment by pearcej** [comment]
@njounkengdaizem Can you please explain the issue further? I don't see what you are meaning.

**Comment by daizenj** [comment]
Wow this is very old, I have tried to find the exact issue but don't even remember. Would recommend closing this issue. Most likely stale @pearcej

**Comment by daizenj** [comment]
Stale issue

**Comment by pearcej** [comment]
yeah, it was added to a fork rather than to the main repo...
